#!/usr/bin/env python3
"""Apply the confirmed subjective attributes from the grid export. $0, no API calls.

    python3 scripts/apply_attrs.py ~/Downloads/attributes.json   # -> scripts/attrs.sql

Then:
    railway run --service Postgres bash -c \\
      '/opt/homebrew/opt/libpq/bin/psql "$DATABASE_PUBLIC_URL" -v ON_ERROR_STOP=1 -f scripts/attrs.sql'

Only touches formality, warmth and season_tags — the three user-owned columns
backfill.py deliberately leaves alone. season_tags is derived from confirmed
warmth rather than asked for separately.

By default only garments listed in `touched` are written, so a partially-filled
grid can be applied safely. Pass --all to write every row in the export.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_SQL = os.path.join(HERE, "attrs.sql")

# Warmth -> seasons. A garment is tagged for the seasons it is actually wearable in.
SEASONS = {
    1: ["summer"],
    2: ["spring", "summer", "fall"],
    3: ["spring", "fall"],
    4: ["fall", "winter"],
    5: ["winter"],
}

SQL_TEMPLATE = """-- GENERATED by scripts/apply_attrs.py from the confirmation grid. Do not hand-edit.
-- Requires migrations/0003_garment_volume.sql.
BEGIN;

UPDATE garment g SET
    formality   = x.formality,
    warmth      = x.warmth,
    season_tags = x.season_tags,
    volume      = x.volume,
    subcategory = x.subcategory
FROM jsonb_to_recordset($attrs${attrs}$attrs$::jsonb)
  AS x(id text, formality int, warmth int, season_tags text[], volume text,
       subcategory text)
WHERE g.id = x.id;

COMMIT;
"""

VOLUMES = {"fitted", "relaxed", "oversized"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export", help="attributes.json downloaded from attr_grid.html")
    ap.add_argument("--all", action="store_true",
                    help="apply every row, not just the ones marked touched")
    args = ap.parse_args()

    with open(os.path.expanduser(args.export)) as fh:
        payload = json.load(fh)

    attrs = payload.get("attributes", {})
    touched = set(payload.get("touched", []))
    if not args.all:
        attrs = {k: v for k, v in attrs.items() if k in touched}

    rows = []
    bad = []
    for gid, v in sorted(attrs.items()):
        f, w = v.get("formality"), v.get("warmth")
        vol, sub = v.get("volume"), v.get("subcategory")
        if not (isinstance(f, int) and 1 <= f <= 5 and isinstance(w, int) and 1 <= w <= 5):
            bad.append((gid, f, w))
            continue
        if vol is not None and vol not in VOLUMES:
            bad.append((gid, "volume", vol))
            continue
        rows.append({"id": gid, "formality": f, "warmth": w, "season_tags": SEASONS[w],
                     "volume": vol, "subcategory": sub})

    if bad:
        print(f"!! {len(bad)} rows out of range, skipped: {bad}", file=sys.stderr)
    if not rows:
        print("nothing to apply (grid export has no touched rows — use --all to force)",
              file=sys.stderr)
        return 1

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(attrs=json.dumps(rows, indent=1)))

    skipped = len(payload.get("attributes", {})) - len(rows)
    print(f"{len(rows)} garments -> {os.path.relpath(OUT_SQL)}"
          + (f"   ({skipped} untouched, left as-is)" if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
