#!/usr/bin/env python3
"""Merge confirmed occasions into outfit.context. $0, no API calls.

    python3 scripts/apply_occasions.py ~/Downloads/occasions.json   # -> scripts/occasions.sql

Merges rather than replaces: outfit.context already carries the look's mechanical
data (title, pose, render filenames) written by backfill.py, and that must survive.
Only looks present in the export are touched.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_SQL = os.path.join(HERE, "occasions.sql")

SQL_TEMPLATE = """-- GENERATED by scripts/apply_occasions.py. Do not hand-edit.
BEGIN;

-- `||` merges the new keys into the existing context rather than replacing it,
-- preserving title/pose/render written by backfill.py.
UPDATE outfit o SET context = o.context || x.patch
FROM jsonb_to_recordset($occ${occ}$occ$::jsonb) AS x(look_id text, patch jsonb)
WHERE o.render_cache_key = x.look_id;

COMMIT;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export", help="occasions.json downloaded from occasion_form.html")
    args = ap.parse_args()

    with open(os.path.expanduser(args.export)) as fh:
        payload = json.load(fh)

    rows = []
    for look_id, v in sorted(payload.get("looks", {}).items()):
        patch = {k: v.get(k) for k in ("occasion", "time", "venue") if v.get(k)}
        if not patch.get("occasion"):
            continue
        rows.append({"look_id": look_id, "patch": patch})

    if not rows:
        print("nothing to apply — no look has an occasion set", file=sys.stderr)
        return 1

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(occ=json.dumps(rows, indent=1)))
    print(f"{len(rows)} looks -> {os.path.relpath(OUT_SQL)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
