#!/usr/bin/env python3
"""Persist blind-calibration verdicts into interaction_log. $0, no API calls.

    python3 scripts/apply_ranking_verdicts.py ~/Downloads/ranking_verdicts.json

Her judgements are the only measured signal that predicts her taste (learned
affinity AUC 0.824 against colour's 0.491), so they belong in the database, not
in a file in Downloads.

Engine picks she judged are inserted as `outfit` rows with source='stylist' —
they are proposals that were shown and ruled on, which is exactly what that
source value means. Her own looks already exist and are matched by look id.
Verdicts land in interaction_log as 'favourited' / 'rejected'.

Idempotent: re-running replaces this batch rather than appending duplicates,
keyed by reason_code.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_SQL = os.path.join(HERE, "ranking_verdicts.sql")
BATCH = "blind-calibration-2026-07-25"

SQL_TEMPLATE = """-- GENERATED by scripts/apply_ranking_verdicts.py. Do not hand-edit.
BEGIN;

CREATE TEMP TABLE _v (key text, ids text[], origin text, verdict text) ON COMMIT DROP;
INSERT INTO _v SELECT key, ids, origin, verdict
FROM jsonb_to_recordset($v${rows}$v$::jsonb)
  AS x(key text, ids text[], origin text, verdict text);

-- Engine proposals that were shown and judged become outfit rows. Her own looks
-- already exist; match those by look id instead of inserting duplicates.
INSERT INTO outfit (garment_ids, source, context, render_cache_key)
SELECT ids, 'stylist', jsonb_build_object('batch', '{batch}'), key
FROM _v WHERE origin = 'engine'
ON CONFLICT (render_cache_key) WHERE render_cache_key IS NOT NULL DO NOTHING;

-- Replace this batch rather than appending on re-run.
DELETE FROM interaction_log WHERE reason_code = '{batch}';

INSERT INTO interaction_log (type, outfit_id, reason_code)
SELECT CASE WHEN v.verdict = 'yes' THEN 'favourited' ELSE 'rejected' END,
       o.id, '{batch}'
FROM _v v
JOIN outfit o ON o.render_cache_key = CASE
    WHEN v.origin = 'engine' THEN v.key
    ELSE replace(v.key, 'look:', '')
END;

COMMIT;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("verdicts")
    args = ap.parse_args()

    with open(os.path.expanduser(args.verdicts)) as fh:
        payload = json.load(fh)
    items = {i["key"]: i for i in payload.get("items", [])}

    rows = []
    for key, verdict in sorted(payload.get("verdicts", {}).items()):
        it = items.get(key)
        if not it or verdict not in ("yes", "no"):
            continue
        rows.append({"key": key, "ids": it["ids"], "origin": it["origin"],
                     "verdict": verdict})
    if not rows:
        print("no usable verdicts", file=sys.stderr)
        return 1

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(rows=json.dumps(rows, indent=1), batch=BATCH))
    yes = sum(1 for r in rows if r["verdict"] == "yes")
    print("%d verdicts (%d favourited, %d rejected) -> %s"
          % (len(rows), yes, len(rows) - yes, os.path.relpath(OUT_SQL)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
