#!/usr/bin/env python3
"""Turn the wear-occasion export into SQL. $0, no API calls.

    python3 scripts/apply_wear_context.py ~/Downloads/wear_context.json
    # -> scripts/wear_context.sql

Generates SQL rather than writing directly, matching apply_occasions.py and
apply_purchase.py: the statement is reviewable before it touches production, and
it runs through the same psql path as every migration.

Addresses rows by `wear_id` where the export has one. Falls back to
(outfit_id, worn_on), which is unique in practice — she logs one wear a day —
but is stated here rather than assumed, and the generated SQL asserts it.
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_SQL = os.path.join(HERE, "wear_context.sql")

VALID = {"work_home", "work_out", "day_out", "dinner", "event", "home"}

SQL = """-- GENERATED by scripts/apply_wear_context.py. Do not hand-edit.
-- Occasion backfill for wears logged before migration 0006.
-- Only rows she actually tapped are present; a blank was never exported.
BEGIN;

CREATE TEMP TABLE wear_patch (
    wear_id   uuid,
    outfit_id uuid,
    worn_on   date,
    occasion  text
) ON COMMIT DROP;

INSERT INTO wear_patch (wear_id, outfit_id, worn_on, occasion)
SELECT nullif(x.wear_id,'')::uuid, nullif(x.outfit_id,'')::uuid,
       x.worn_on::date, x.occasion
  FROM jsonb_to_recordset($wear${rows}$wear$::jsonb)
    AS x(wear_id text, outfit_id text, worn_on text, occasion text);

-- The fallback match must be unique or it would write one answer onto two days.
-- Fail loudly here rather than quietly mislabelling the training data.
DO $$
DECLARE dupes int;
BEGIN
  SELECT count(*) INTO dupes FROM (
    SELECT w.id FROM wear_log w
      JOIN wear_patch p
        ON p.wear_id IS NULL
       AND w.outfit_id = p.outfit_id AND w.worn_on = p.worn_on
     GROUP BY w.id HAVING count(*) > 1) t;
  IF dupes > 0 THEN
    RAISE EXCEPTION 'ambiguous match for % row(s) — address them by wear_id', dupes;
  END IF;
END $$;

UPDATE wear_log w SET occasion = p.occasion
  FROM wear_patch p
 WHERE (p.wear_id IS NOT NULL AND w.id = p.wear_id)
    OR (p.wear_id IS NULL AND w.outfit_id = p.outfit_id AND w.worn_on = p.worn_on);

-- acceptance: how many wears now carry an occasion, and in what mix
SELECT coalesce(occasion, '(none)') AS occasion, count(*)
  FROM wear_log GROUP BY 1 ORDER BY 2 DESC;

COMMIT;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export", help="wear_context.json from wear_form.html")
    args = ap.parse_args()

    with open(os.path.expanduser(args.export)) as fh:
        payload = json.load(fh)

    rows = []
    for w in payload.get("wears", []):
        occ = (w.get("occasion") or "").strip()
        if not occ:
            continue
        if occ not in VALID:
            raise SystemExit("unknown occasion %r — valid: %s"
                             % (occ, ", ".join(sorted(VALID))))
        if not w.get("wear_id") and not (w.get("outfit_id") and w.get("worn_on")):
            raise SystemExit("row has neither wear_id nor (outfit_id, worn_on): %r" % w)
        rows.append({"wear_id": w.get("wear_id") or "",
                     "outfit_id": w.get("outfit_id") or "",
                     "worn_on": w.get("worn_on"),
                     "occasion": occ})

    if not rows:
        raise SystemExit("nothing to apply — no row carried an occasion")

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL.format(rows=json.dumps(rows, indent=2)))

    by_id = sum(1 for r in rows if r["wear_id"])
    print("%d occasion(s) -> %s" % (len(rows), os.path.relpath(OUT_SQL)))
    print("  addressed by wear_id: %d · by (outfit_id, worn_on): %d"
          % (by_id, len(rows) - by_id))
    print("\nrun it with:")
    print('  railway run --service Postgres bash -c '
          "'/opt/homebrew/opt/libpq/bin/psql \"$DATABASE_PUBLIC_URL\" "
          "-v ON_ERROR_STOP=1 -f %s'" % os.path.relpath(OUT_SQL))


if __name__ == "__main__":
    main()
