#!/usr/bin/env python3
"""Apply purchase data into garment.purchase. $0, no API calls.

    python3 scripts/apply_purchase.py ~/Downloads/purchases.json  # -> scripts/purchase.sql

Accepts the browser form's JSON export, or a filled purchase.tsv (detected by
extension) for anyone who prefers an editor. Merges with `||` so re-running with a
partial file never clears fields set earlier. Blank entries are skipped.
"""
import argparse
import csv
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_SQL = os.path.join(HERE, "purchase.sql")

SQL_TEMPLATE = """-- GENERATED by scripts/apply_purchase.py. Do not hand-edit.
BEGIN;

-- `||` merges: a later partial fill must not wipe earlier values.
UPDATE garment g SET purchase = g.purchase || x.purchase
FROM jsonb_to_recordset($pur${rows}$pur$::jsonb) AS x(id text, purchase jsonb)
WHERE g.id = x.id;

COMMIT;
"""


def coerce(gid, price, when, source, bad):
    purchase = {}
    if price:
        try:
            purchase["price_usd"] = round(float(re.sub(r"[^0-9.]", "", str(price))), 2)
        except ValueError:
            bad.append((gid, "price", price))
            return None
    if when:
        if not re.match(r"^\d{4}(-\d{2})?(-\d{2})?$", str(when)):
            bad.append((gid, "purchased", when))
            return None
        purchase["date"] = str(when)
    if source:
        purchase["source"] = str(source).strip()
    return purchase or None


def from_json(path, bad):
    with open(path) as fh:
        payload = json.load(fh)
    rows = []
    for gid, v in sorted(payload.get("purchases", {}).items()):
        p = coerce(gid, v.get("price_usd"), v.get("purchased"), v.get("source"), bad)
        if p:
            rows.append({"id": gid, "purchase": p})
    return rows


def from_tsv(path, bad):
    rows = []
    with open(path, newline="") as fh:
        for rec in csv.DictReader(fh, delimiter="\t"):
            gid = (rec.get("id") or "").strip()
            if not gid or gid.startswith("#"):
                continue
            p = coerce(gid, (rec.get("price_usd") or "").strip(),
                       (rec.get("purchased") or "").strip(),
                       (rec.get("source") or "").strip(), bad)
            if p:
                rows.append({"id": gid, "purchase": p})
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("export", help="purchases.json from the form, or a filled purchase.tsv")
    args = ap.parse_args()
    path = os.path.expanduser(args.export)

    bad = []
    rows = from_tsv(path, bad) if path.endswith(".tsv") else from_json(path, bad)

    if bad:
        print(f"!! {len(bad)} unparseable cells, skipped: {bad}", file=sys.stderr)
    if not rows:
        print("nothing filled in yet", file=sys.stderr)
        return 1

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(rows=json.dumps(rows, indent=1)))

    priced = [r["purchase"]["price_usd"] for r in rows if "price_usd" in r["purchase"]]
    print(f"{len(rows)} garments -> {os.path.relpath(OUT_SQL)}")
    if priced:
        print(f"  {len(priced)} with a price, total ${sum(priced):,.2f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
