#!/usr/bin/env python3
"""Emit a fill-in TSV for purchase data, and read it back. $0, no API calls.

    python3 scripts/make_purchase_tsv.py            # -> scripts/purchase.tsv (fill in Sublime)
    python3 scripts/make_purchase_tsv.py --apply    # purchase.tsv -> scripts/purchase.sql

`garment.purchase` is {{}} for all 58 and cannot be reconstructed later — it is the
one input Track C (cost-per-wear, sustainability) is arithmetically impossible
without. Approximate is fine: a price to the nearest ten and a YYYY-MM is plenty.

TSV, not CSV, because brand and garment names contain commas. Tab-separated columns
survive a paste into any editor. Blank rows are skipped, so partial fills are safe.
An existing purchase.tsv is never overwritten — regenerating preserves your edits.
"""
import argparse
import csv
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CLOSET = os.path.normpath(os.path.join(HERE, "..", "..", "virtual-closet"))
GARMENTS = os.path.join(CLOSET, "garments")
TSV = os.path.join(HERE, "purchase.tsv")
OUT_SQL = os.path.join(HERE, "purchase.sql")

COLUMNS = ["id", "name", "brand", "size", "price_usd", "purchased", "source"]

SQL_TEMPLATE = """-- GENERATED by scripts/make_purchase_tsv.py --apply. Do not hand-edit.
BEGIN;

UPDATE garment g SET purchase = g.purchase || x.purchase
FROM jsonb_to_recordset($pur${rows}$pur$::jsonb) AS x(id text, purchase jsonb)
WHERE g.id = x.id;

COMMIT;
"""


def read_metas():
    out = []
    for gid in sorted(os.listdir(GARMENTS)):
        d = os.path.join(GARMENTS, gid)
        if not os.path.isdir(d) or gid in ("raw", "archive"):
            continue
        mp = os.path.join(d, "meta.json")
        if not os.path.exists(mp):
            continue
        with open(mp) as fh:
            m = json.load(fh)
        out.append((gid, m.get("name", ""), m.get("brand", ""), m.get("size_owned", "")))
    return out


def generate():
    if os.path.exists(TSV):
        print(f"{os.path.relpath(TSV)} already exists — not overwriting your edits.")
        return
    with open(TSV, "w", newline="") as fh:
        w = csv.writer(fh, delimiter="\t")
        w.writerow(COLUMNS)
        w.writerow(["# fill price_usd (number, approx ok), purchased (YYYY-MM),",
                    "source (shop/site).", "leave a row blank to skip it.", "", "", "", ""])
        for gid, name, brand, size in read_metas():
            w.writerow([gid, name, brand, size, "", "", ""])
    print(f"{len(read_metas())} rows -> {os.path.relpath(TSV)}")


def apply():
    if not os.path.exists(TSV):
        print("no purchase.tsv — run without --apply first", file=sys.stderr)
        return 1
    rows, bad = [], []
    with open(TSV, newline="") as fh:
        for rec in csv.DictReader(fh, delimiter="\t"):
            gid = (rec.get("id") or "").strip()
            if not gid or gid.startswith("#"):
                continue
            price = (rec.get("price_usd") or "").strip()
            when = (rec.get("purchased") or "").strip()
            source = (rec.get("source") or "").strip()
            if not (price or when or source):
                continue                      # untouched row
            purchase = {}
            if price:
                cleaned = re.sub(r"[^0-9.]", "", price)
                try:
                    purchase["price_usd"] = round(float(cleaned), 2)
                except ValueError:
                    bad.append((gid, "price", price))
                    continue
            if when:
                if not re.match(r"^\d{4}(-\d{2})?(-\d{2})?$", when):
                    bad.append((gid, "purchased", when))
                    continue
                purchase["date"] = when
            if source:
                purchase["source"] = source
            rows.append({"id": gid, "purchase": purchase})

    if bad:
        print(f"!! {len(bad)} unparseable cells, skipped: {bad}", file=sys.stderr)
    if not rows:
        print("nothing filled in yet", file=sys.stderr)
        return 1
    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(rows=json.dumps(rows, indent=1)))
    print(f"{len(rows)} garments -> {os.path.relpath(OUT_SQL)}")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    sys.exit(apply() if a.apply else (generate() or 0))
