-- GENERATED by scripts/apply_ranking_verdicts.py. Do not hand-edit.
BEGIN;

CREATE TEMP TABLE _v (key text, ids text[], origin text, verdict text) ON COMMIT DROP;
INSERT INTO _v SELECT key, ids, origin, verdict
FROM jsonb_to_recordset($v$[
 {
  "key": "engine:07-aritzia-suit-vest+47-woodrose-deli-skirt+52-camper-flats",
  "ids": [
   "07-aritzia-suit-vest",
   "47-woodrose-deli-skirt",
   "52-camper-flats"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:07-aritzia-suit-vest+47-woodrose-deli-skirt+53-keen-sandals",
  "ids": [
   "07-aritzia-suit-vest",
   "47-woodrose-deli-skirt",
   "53-keen-sandals"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:09-bunnyhill-white-top+32-personal-language-skirt+57-puma-ssg-sneakers",
  "ids": [
   "09-bunnyhill-white-top",
   "32-personal-language-skirt",
   "57-puma-ssg-sneakers"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "engine:09-bunnyhill-white-top+32-personal-language-skirt+58-vortex-long-boots",
  "ids": [
   "09-bunnyhill-white-top",
   "32-personal-language-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "engine:09-bunnyhill-white-top+44-subtle-mermaid-skirt+55-asics-sneakers",
  "ids": [
   "09-bunnyhill-white-top",
   "44-subtle-mermaid-skirt",
   "55-asics-sneakers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:11-coucou-black-muse-tank+10-coucou-black-midi-skirt+56-mizuno-sneakers",
  "ids": [
   "11-coucou-black-muse-tank",
   "10-coucou-black-midi-skirt",
   "56-mizuno-sneakers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:11-coucou-black-muse-tank+44-subtle-mermaid-skirt+51-weejuns-loafers",
  "ids": [
   "11-coucou-black-muse-tank",
   "44-subtle-mermaid-skirt",
   "51-weejuns-loafers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:13-coucou-long-sleeve-top+18-coucou-white-midi-skirt+53-keen-sandals",
  "ids": [
   "13-coucou-long-sleeve-top",
   "18-coucou-white-midi-skirt",
   "53-keen-sandals"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:17-coucou-slip-dress+50-yello-heels",
  "ids": [
   "17-coucou-slip-dress",
   "50-yello-heels"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:19-coucou-white-scoop-tank+10-coucou-black-midi-skirt+50-yello-heels",
  "ids": [
   "19-coucou-white-scoop-tank",
   "10-coucou-black-midi-skirt",
   "50-yello-heels"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:19-coucou-white-scoop-tank+32-personal-language-skirt+58-vortex-long-boots",
  "ids": [
   "19-coucou-white-scoop-tank",
   "32-personal-language-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:23-issey-black-tank+42-sagittarius-trousers+51-weejuns-loafers",
  "ids": [
   "23-issey-black-tank",
   "42-sagittarius-trousers",
   "51-weejuns-loafers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:25-kotn-samira-tank+02-jeans+54-salomon-sneakers",
  "ids": [
   "25-kotn-samira-tank",
   "02-jeans",
   "54-salomon-sneakers"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "engine:25-kotn-samira-tank+18-coucou-white-midi-skirt+54-salomon-sneakers",
  "ids": [
   "25-kotn-samira-tank",
   "18-coucou-white-midi-skirt",
   "54-salomon-sneakers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:29-nin-pleated-top+27-liniss-pants+54-salomon-sneakers",
  "ids": [
   "29-nin-pleated-top",
   "27-liniss-pants",
   "54-salomon-sneakers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:30-off-shoulder-top+10-coucou-black-midi-skirt+49-jil-sander-boots",
  "ids": [
   "30-off-shoulder-top",
   "10-coucou-black-midi-skirt",
   "49-jil-sander-boots"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "engine:30-off-shoulder-top+18-coucou-white-midi-skirt+58-vortex-long-boots",
  "ids": [
   "30-off-shoulder-top",
   "18-coucou-white-midi-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:31-orseund-iris-top+18-coucou-white-midi-skirt+58-vortex-long-boots",
  "ids": [
   "31-orseund-iris-top",
   "18-coucou-white-midi-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:31-orseund-iris-top+32-personal-language-skirt+58-vortex-long-boots",
  "ids": [
   "31-orseund-iris-top",
   "32-personal-language-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:37-realisation-gia-dress+51-weejuns-loafers",
  "ids": [
   "37-realisation-gia-dress",
   "51-weejuns-loafers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:41-sagittarius-top+18-coucou-white-midi-skirt+58-vortex-long-boots",
  "ids": [
   "41-sagittarius-top",
   "18-coucou-white-midi-skirt",
   "58-vortex-long-boots"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:43-subtle-mermaid-top+44-subtle-mermaid-skirt+52-camper-flats",
  "ids": [
   "43-subtle-mermaid-top",
   "44-subtle-mermaid-skirt",
   "52-camper-flats"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "engine:45-sundae-gorum-shirt+27-liniss-pants+54-salomon-sneakers",
  "ids": [
   "45-sundae-gorum-shirt",
   "27-liniss-pants",
   "54-salomon-sneakers"
  ],
  "origin": "engine",
  "verdict": "no"
 },
 {
  "key": "engine:48-woodrose-deli-sweater+47-woodrose-deli-skirt+52-camper-flats",
  "ids": [
   "48-woodrose-deli-sweater",
   "47-woodrose-deli-skirt",
   "52-camper-flats"
  ],
  "origin": "engine",
  "verdict": "yes"
 },
 {
  "key": "look:look-005",
  "ids": [
   "01-plain-tee",
   "02-jeans",
   "50-yello-heels"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-006",
  "ids": [
   "03-patterned-dress",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-007",
  "ids": [
   "11-coucou-black-muse-tank",
   "10-coucou-black-midi-skirt",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-008",
  "ids": [
   "23-issey-black-tank",
   "02-jeans",
   "50-yello-heels"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-009",
  "ids": [
   "24-issey-silver-tank",
   "32-personal-language-skirt",
   "53-keen-sandals"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-010",
  "ids": [
   "29-nin-pleated-top",
   "15-coucou-mini-skirt",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-011",
  "ids": [
   "08-bunnyhill-grey-top",
   "26-liniss-dune-pants",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-012",
  "ids": [
   "25-kotn-samira-tank",
   "32-personal-language-skirt",
   "53-keen-sandals"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-013",
  "ids": [
   "30-off-shoulder-top",
   "27-liniss-pants",
   "50-yello-heels"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-014",
  "ids": [
   "48-woodrose-deli-sweater",
   "47-woodrose-deli-skirt",
   "49-jil-sander-boots"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-016",
  "ids": [
   "05-hardest-item",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-017",
  "ids": [
   "35-realisation-delphine-dress",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-018",
  "ids": [
   "37-realisation-gia-dress",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-019",
  "ids": [
   "38-realisation-iggy-dress",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-020",
  "ids": [
   "46-the-idiot-jacket",
   "25-kotn-samira-tank",
   "02-jeans",
   "57-puma-ssg-sneakers"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-021",
  "ids": [
   "06-aritzia-slouch-coat",
   "02-jeans",
   "07-aritzia-suit-vest",
   "55-asics-sneakers"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-022",
  "ids": [
   "09-bunnyhill-white-top",
   "44-subtle-mermaid-skirt",
   "52-camper-flats"
  ],
  "origin": "hers",
  "verdict": "yes"
 },
 {
  "key": "look:look-023",
  "ids": [
   "59-el-hoodie",
   "42-sagittarius-trousers",
   "56-mizuno-sneakers"
  ],
  "origin": "hers",
  "verdict": "yes"
 }
]$v$::jsonb)
  AS x(key text, ids text[], origin text, verdict text);

-- Engine proposals that were shown and judged become outfit rows. Her own looks
-- already exist; match those by look id instead of inserting duplicates.
INSERT INTO outfit (garment_ids, source, context, render_cache_key)
SELECT ids, 'stylist', jsonb_build_object('batch', 'blind-calibration-2026-07-25'), key
FROM _v WHERE origin = 'engine'
ON CONFLICT (render_cache_key) WHERE render_cache_key IS NOT NULL DO NOTHING;

-- Replace this batch rather than appending on re-run.
DELETE FROM interaction_log WHERE reason_code = 'blind-calibration-2026-07-25';

INSERT INTO interaction_log (type, outfit_id, reason_code)
SELECT CASE WHEN v.verdict = 'yes' THEN 'favourited' ELSE 'rejected' END,
       o.id, 'blind-calibration-2026-07-25'
FROM _v v
JOIN outfit o ON o.render_cache_key = CASE
    WHEN v.origin = 'engine' THEN v.key
    ELSE replace(v.key, 'look:', '')
END;

COMMIT;
