#!/usr/bin/env python3
"""Push local stylist feedback into Postgres. $0, no API calls.

    python3 scripts/sync_stylist_feedback.py          # -> scripts/stylist_feedback.sql

The stylist runs local-only (deliberate: shipping APP_SECRET into a public page
would undo the auth guardrail that the hosted-Postgres reversal depends on), so
its feedback lands in virtual-closet/logs/stylist_feedback.jsonl. This carries it
into the database, where it belongs alongside the calibration verdicts.

The blamed garment is stored in interaction_log.reason_code — which garment
killed an outfit is the whole reason attributed rejections are usable at all.
Idempotent: keyed on the log timestamp, so re-running syncs only what is new.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = os.path.normpath(os.path.join(
    HERE, "..", "..", "virtual-closet", "logs", "stylist_feedback.jsonl"))
OUT_SQL = os.path.join(HERE, "stylist_feedback.sql")

SQL_TEMPLATE = """-- GENERATED by scripts/sync_stylist_feedback.py. Do not hand-edit.
BEGIN;

CREATE TEMP TABLE _f (ts text, ids text[], verdict text, blame text, occasion text)
  ON COMMIT DROP;
INSERT INTO _f SELECT ts, ids, verdict, blame, occasion
FROM jsonb_to_recordset($f${rows}$f$::jsonb)
  AS x(ts text, ids text[], verdict text, blame text, occasion text);

-- Each judged suggestion becomes an outfit row; the timestamp is its key, so a
-- re-sync updates rather than duplicating.
INSERT INTO outfit (garment_ids, source, context, render_cache_key)
SELECT ids, 'stylist',
       jsonb_strip_nulls(jsonb_build_object('occasion', nullif(occasion, ''),
                                            'from', 'stylist-v1')),
       'stylist:' || ts
FROM _f
ON CONFLICT (render_cache_key) WHERE render_cache_key IS NOT NULL DO NOTHING;

DELETE FROM interaction_log
WHERE outfit_id IN (SELECT id FROM outfit WHERE render_cache_key LIKE 'stylist:%');

INSERT INTO interaction_log (type, outfit_id, reason_code)
SELECT CASE WHEN f.verdict = 'yes' THEN 'favourited' ELSE 'rejected' END,
       o.id,
       f.blame            -- which garment killed it; NULL for an acceptance
FROM _f f JOIN outfit o ON o.render_cache_key = 'stylist:' || f.ts;

COMMIT;
"""


def main():
    if not os.path.exists(LOG):
        print("no stylist feedback yet (%s)" % LOG)
        return 0
    rows = []
    with open(LOG) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except ValueError:
                continue
            if not e.get("ids") or e.get("verdict") not in ("yes", "no"):
                continue
            rows.append({"ts": e.get("ts"), "ids": e["ids"], "verdict": e["verdict"],
                         "blame": e.get("blame"), "occasion": e.get("occasion") or ""})
    if not rows:
        print("nothing to sync")
        return 0

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL_TEMPLATE.format(rows=json.dumps(rows, indent=1)))
    yes = sum(1 for r in rows if r["verdict"] == "yes")
    blamed = sum(1 for r in rows if r["blame"])
    print("%d judgements (%d worn, %d rejected, %d attributed) -> %s"
          % (len(rows), yes, len(rows) - yes, blamed, os.path.relpath(OUT_SQL)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
