-- GENERATED by scripts/apply_wear_context.py. Do not hand-edit.
-- Occasion backfill for wears logged before migration 0006.
-- Only rows she actually tapped are present; a blank was never exported.
BEGIN;

CREATE TEMP TABLE wear_patch (
    wear_id   uuid,
    outfit_id uuid,
    worn_on   date,
    occasion  text
) ON COMMIT DROP;

INSERT INTO wear_patch (wear_id, outfit_id, worn_on, occasion)
SELECT nullif(x.wear_id,'')::uuid, nullif(x.outfit_id,'')::uuid,
       x.worn_on::date, x.occasion
  FROM jsonb_to_recordset($wear$[
  {
    "wear_id": "b7315df7-9b8f-4e58-a64f-80b40e7c9a60",
    "outfit_id": "2eebb0b8-6591-4a0a-8e30-4eeb285e8141",
    "worn_on": "2026-07-13",
    "occasion": "work_out"
  },
  {
    "wear_id": "0cf6b986-d872-4b58-bfab-ff71646b83d5",
    "outfit_id": "37acd301-722c-49c8-b878-bc5081f33156",
    "worn_on": "2026-07-14",
    "occasion": "work_home"
  },
  {
    "wear_id": "f395f66b-8036-4a1b-8953-d23b25d4dfc3",
    "outfit_id": "a25a8539-214a-434d-b628-62e2cc01334d",
    "worn_on": "2026-07-15",
    "occasion": "work_home"
  },
  {
    "wear_id": "4b9425fc-5c31-40f8-938c-3be4ca99b2c7",
    "outfit_id": "858ce733-06be-4c00-8618-695b7b663a12",
    "worn_on": "2026-07-16",
    "occasion": "dinner"
  },
  {
    "wear_id": "5c822f66-dbaa-48c2-a6a9-fe2bd4699446",
    "outfit_id": "a7a667cc-acf9-474d-9621-ce1bac27d0e4",
    "worn_on": "2026-07-17",
    "occasion": "dinner"
  },
  {
    "wear_id": "eaf0863e-2f88-4f29-9bdf-3e6b6883fe97",
    "outfit_id": "a91bc510-5577-4f42-81aa-0c7bc2c14297",
    "worn_on": "2026-07-18",
    "occasion": "dinner"
  },
  {
    "wear_id": "c504b743-f3f4-4d30-927d-559d6f7021d5",
    "outfit_id": "9de4fee9-d3c8-450f-a478-f9ee7c08fab5",
    "worn_on": "2026-07-19",
    "occasion": "day_out"
  },
  {
    "wear_id": "f796f729-ab0c-4eea-a45a-60090a06f212",
    "outfit_id": "dd67b4b8-4551-43fe-ba02-fb273c177850",
    "worn_on": "2026-07-20",
    "occasion": "day_out"
  },
  {
    "wear_id": "8c2fdcd2-4085-445e-a76e-7341dfa42232",
    "outfit_id": "409c2d60-105d-4435-97b9-45c4ab194663",
    "worn_on": "2026-07-21",
    "occasion": "day_out"
  },
  {
    "wear_id": "10f674d2-ebaf-4427-a6d2-377e46bc3b14",
    "outfit_id": "d2663e4e-3130-4d30-acc3-2fcca1813d99",
    "worn_on": "2026-07-22",
    "occasion": "dinner"
  },
  {
    "wear_id": "3fa9d937-0a89-4831-82dd-8f857b11ada0",
    "outfit_id": "d8b086b4-d9f5-49a5-87d3-37fff34171c6",
    "worn_on": "2026-07-23",
    "occasion": "work_out"
  },
  {
    "wear_id": "09ebd301-b405-40f7-b2ba-c41e69a8654a",
    "outfit_id": "d2b1c21c-417b-41c7-8d9b-9916bdf3e8a5",
    "worn_on": "2026-07-24",
    "occasion": "day_out"
  },
  {
    "wear_id": "5b7ca32c-e16f-4c29-90b6-7cc9eb8b741d",
    "outfit_id": "1a290369-9de6-4363-bfb8-ffc06cda7285",
    "worn_on": "2026-07-25",
    "occasion": "dinner"
  },
  {
    "wear_id": "0a1ff94a-1ac4-439a-a182-ecff3de84c4a",
    "outfit_id": "ee8e0c67-7cc2-4302-8e4c-1b9c29bd07ce",
    "worn_on": "2026-07-26",
    "occasion": "dinner"
  },
  {
    "wear_id": "2ed96952-eea8-49c4-ac9e-315005b0a35e",
    "outfit_id": "37d15d7e-01e3-4f5f-bc37-d295e457c837",
    "worn_on": "2026-07-27",
    "occasion": "work_home"
  }
]$wear$::jsonb)
    AS x(wear_id text, outfit_id text, worn_on text, occasion text);

-- The fallback match must be unique or it would write one answer onto two days.
-- Fail loudly here rather than quietly mislabelling the training data.
DO $$
DECLARE dupes int;
BEGIN
  SELECT count(*) INTO dupes FROM (
    SELECT w.id FROM wear_log w
      JOIN wear_patch p
        ON p.wear_id IS NULL
       AND w.outfit_id = p.outfit_id AND w.worn_on = p.worn_on
     GROUP BY w.id HAVING count(*) > 1) t;
  IF dupes > 0 THEN
    RAISE EXCEPTION 'ambiguous match for % row(s) — address them by wear_id', dupes;
  END IF;
END $$;

UPDATE wear_log w SET occasion = p.occasion
  FROM wear_patch p
 WHERE (p.wear_id IS NOT NULL AND w.id = p.wear_id)
    OR (p.wear_id IS NULL AND w.outfit_id = p.outfit_id AND w.worn_on = p.worn_on);

-- acceptance: how many wears now carry an occasion, and in what mix
SELECT coalesce(occasion, '(none)') AS occasion, count(*)
  FROM wear_log GROUP BY 1 ORDER BY 2 DESC;

COMMIT;
