-- GENERATED by scripts/weather_backfill.py. Do not hand-edit.
-- Weather is DERIVED from worn_on, never typed — the one context field that
-- costs nothing to collect. Re-runnable: it only fills rows that are still empty
-- unless the generator was run with --refetch.
BEGIN;

UPDATE wear_log w SET weather = x.weather
  FROM jsonb_to_recordset($wx$[
  {
    "wear_id": "402a6e7b-0248-4b28-9087-59fb232850b5",
    "weather": {
      "temp_max_c": 30.3,
      "temp_min_c": 20.6,
      "precip_mm": 3.6,
      "code": 55,
      "conditions": "rain",
      "source": "open-meteo/archive",
      "lat": 40.7128,
      "lon": -74.006
    }
  },
  {
    "wear_id": "8fcfa40e-6cd3-4a7e-ac3f-790afe3783ab",
    "weather": {
      "temp_max_c": 27.4,
      "temp_min_c": 20.8,
      "precip_mm": 21.0,
      "code": 63,
      "conditions": "rain",
      "source": "open-meteo/archive",
      "lat": 40.7128,
      "lon": -74.006
    }
  },
  {
    "wear_id": "3d30f8c5-1434-44c9-9c27-51228ee5548a",
    "weather": {
      "temp_max_c": 28.0,
      "temp_min_c": 20.9,
      "precip_mm": 37.1,
      "code": 65,
      "conditions": "rain",
      "source": "open-meteo/archive",
      "lat": 40.7128,
      "lon": -74.006
    }
  }
]$wx$::jsonb) AS x(wear_id uuid, weather jsonb)
 WHERE w.id = x.wear_id;

-- acceptance: every wear should now carry a condition and a temperature
SELECT count(*) AS wears,
       count(*) FILTER (WHERE weather <> '{}') AS with_weather,
       count(DISTINCT weather->>'conditions')    AS distinct_conditions
  FROM wear_log;

COMMIT;
