#!/usr/bin/env python3
"""Fill `wear_log.weather` from the date each wear was logged. $0, no API key.

THE POINT: this is the only context field that costs her nothing. Occasion has
to be tapped and the swap has to be remembered; weather is already implied by
`worn_on` and can be recovered for every wear ever logged, and every wear that
ever will be, without a single extra interaction.

Source is Open-Meteo's ARCHIVE endpoint — free, no key, no attribution
requirement, and it serves reanalysis rather than forecasts, so a past date
returns what actually happened rather than what was predicted. The archive lags
real time by ~5 days; days inside that window fall back to the forecast
endpoint, which still holds recent history. Both are recorded in
`weather.source` so a later analysis can tell them apart rather than silently
mixing reanalysis with forecast.

READS THE SNAPSHOT, WRITES SQL — deliberately no database driver. The dates it
needs are already in `closet_snapshot.json`, and generating SQL means this goes
through the same reviewed psql path as every migration instead of requiring
psycopg on a laptop that has never needed one.

    python3 scripts/dump_closet.py                       # snapshot must be current
    python3 scripts/weather_backfill.py --city nyc       # -> scripts/weather.sql
    python3 scripts/weather_backfill.py --city nyc --apply

`--apply` runs it via `railway run --service Postgres`, the same path
dump_closet.py uses.
"""
import argparse
import json
import os
import subprocess
import sys
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, "closet_snapshot.json")
OUT_SQL = os.path.join(HERE, "weather.sql")
PSQL = "/opt/homebrew/opt/libpq/bin/psql"

ARCHIVE = "https://archive-api.open-meteo.com/v1/archive"
FORECAST = "https://api.open-meteo.com/v1/forecast"
DAILY = "temperature_2m_max,temperature_2m_min,precipitation_sum,weather_code"

# Named so the coordinates are recorded rather than retyped from memory each
# time — a silently wrong location would label the data plausibly and wrongly.
CITIES = {
    "nyc": (40.7128, -74.0060, "America/New_York"),
}


def describe(code):
    """WMO code -> a word. Deliberately coarse: this closet will have tens of
    wears, not thousands, so "rain" is a usable category and "light freezing
    drizzle, dense" is not."""
    if code is None:
        return None
    c = int(code)
    if c == 0:
        return "clear"
    if c in (1, 2, 3):
        return "cloud"
    if c in (45, 48):
        return "fog"
    if 51 <= c <= 67 or 80 <= c <= 82:
        return "rain"
    if 71 <= c <= 77 or c in (85, 86):
        return "snow"
    if c >= 95:
        return "storm"
    return "other"


def fetch_range(lat, lon, start, end, tz="auto"):
    """One request per endpoint for the whole span — 15 wears is 2 calls."""
    out = {}
    for base, tag in ((ARCHIVE, "archive"), (FORECAST, "forecast")):
        q = {"latitude": lat, "longitude": lon, "daily": DAILY,
             "timezone": tz, "start_date": start, "end_date": end}
        try:
            with urllib.request.urlopen(base + "?" + urllib.parse.urlencode(q),
                                        timeout=60) as fh:
                data = json.load(fh)
        except Exception as e:                        # noqa: BLE001
            print("  %s unavailable: %s" % (tag, e))
            continue
        d = data.get("daily") or {}
        for i, day in enumerate(d.get("time") or []):
            if day in out:
                continue                              # archive wins; it is reanalysis

            def at(key, i=i, d=d):
                seq = d.get(key) or []
                return seq[i] if i < len(seq) else None

            code = at("weather_code")
            if at("temperature_2m_max") is None and code is None:
                continue
            out[day] = {
                "temp_max_c": at("temperature_2m_max"),
                "temp_min_c": at("temperature_2m_min"),
                "precip_mm": at("precipitation_sum"),
                "code": code,
                "conditions": describe(code),
                "source": "open-meteo/" + tag,
                "lat": lat, "lon": lon,
            }
    return out


SQL = """-- GENERATED by scripts/weather_backfill.py. Do not hand-edit.
-- Weather is DERIVED from worn_on, never typed — the one context field that
-- costs nothing to collect. Re-runnable: it only fills rows that are still empty
-- unless the generator was run with --refetch.
BEGIN;

UPDATE wear_log w SET weather = x.weather
  FROM jsonb_to_recordset($wx${rows}$wx$::jsonb) AS x(wear_id uuid, weather jsonb)
 WHERE w.id = x.wear_id;

-- acceptance: every wear should now carry a condition and a temperature
SELECT count(*) AS wears,
       count(*) FILTER (WHERE weather <> '{{}}') AS with_weather,
       count(DISTINCT weather->>'conditions')    AS distinct_conditions
  FROM wear_log;

COMMIT;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--city", choices=sorted(CITIES))
    ap.add_argument("--lat", type=float)
    ap.add_argument("--lon", type=float)
    ap.add_argument("--timezone", default=None)
    ap.add_argument("--refetch", action="store_true",
                    help="include wears that already have weather")
    ap.add_argument("--apply", action="store_true",
                    help="run the generated SQL via railway psql")
    args = ap.parse_args()

    if args.city:
        lat, lon, tz = CITIES[args.city]
    elif args.lat is not None and args.lon is not None:
        lat, lon, tz = args.lat, args.lon, "auto"
    else:
        sys.exit("give --city (%s) or --lat/--lon" % ", ".join(sorted(CITIES)))
    tz = args.timezone or tz

    with open(SNAPSHOT) as fh:
        wears = json.load(fh).get("wears") or []
    if not wears:
        sys.exit("no wears in the snapshot — run dump_closet.py")
    todo = [w for w in wears if args.refetch or not (w.get("weather") or {})]
    missing_id = [w for w in todo if not w.get("id")]
    if missing_id:
        sys.exit("%d wear(s) have no id — re-run dump_closet.py (0006 or later)"
                 % len(missing_id))
    if not todo:
        print("every wear already has weather — use --refetch to overwrite")
        return

    days = sorted(w["worn_on"] for w in todo)
    print("%d wear(s) to fill, %s -> %s @ %.4f,%.4f (%s)"
          % (len(todo), days[0], days[-1], lat, lon, tz))
    wx = fetch_range(lat, lon, days[0], days[-1], tz)
    print("fetched %d day(s)" % len(wx))

    rows, missed = [], 0
    for w in todo:
        got = wx.get(w["worn_on"])
        if not got:
            missed += 1
            print("  no data  %s" % w["worn_on"])
            continue
        print("  %s  %-6s %s" % (
            w["worn_on"], got["conditions"] or "?",
            ("%.1f–%.1f°C" % (got["temp_min_c"], got["temp_max_c"]))
            if got["temp_max_c"] is not None else "?"))
        rows.append({"wear_id": w["id"], "weather": got})

    if not rows:
        sys.exit("nothing fetched — no SQL written")

    with open(OUT_SQL, "w") as fh:
        fh.write(SQL.format(rows=json.dumps(rows, indent=2)))
    print("\n%d row(s) -> %s%s"
          % (len(rows), os.path.relpath(OUT_SQL),
             "  (%d without data)" % missed if missed else ""))

    if not args.apply:
        print("\nreview it, then re-run with --apply")
        return

    cmd = ["railway", "run", "--service", "Postgres", "bash", "-c",
           '%s "$DATABASE_PUBLIC_URL" -v ON_ERROR_STOP=1 -f %s' % (PSQL, OUT_SQL)]
    res = subprocess.run(cmd, capture_output=True, text=True)
    sys.stdout.write(res.stdout)
    if res.returncode != 0:
        sys.stderr.write(res.stderr[-2000:])
        sys.exit(res.returncode)


if __name__ == "__main__":
    main()
